"""Build the h-sets for the P^4 horseshoe at A = gamma_rel. Geometry comes from non-rigorous numerics (band line fit + local stable direction); the proof itself is the interval check in horseshoe.cpp."""
import subprocess, numpy as np, sys
a, b = 0.3474593836, -1.2631610188           # left-band line z = a y + b (fit to the attractor section, residual 7.8e-6)
J1 = (1.9116575742804343, 1.9119251153342618); J2 = (1.9120964286836524, 1.9124471197093345)
w = float(sys.argv[1]) if len(sys.argv) > 1 else 1.5e-4
lines = ["# P^4 horseshoe h-sets (u along the attractor band, s along the local stable direction of P^4). Generated by mk_hsets.py", "iterate 4"]
P = np.load('section_gammarel.npy'); Y, Z = P[:, 1], P[:, 2]
for name, (y0, y1) in (("N1", J1), ("N2", J2)):
    yc = 0.5 * (y0 + y1); hl = 0.5 * (y1 - y0); m = np.abs(Y - yc) < 1.5 * hl; a, b = np.polyfit(Y[m], Z[m], 1); zc = a * yc + b  # local band line
    o = subprocess.run(['./horseshoe', 'map', '2', '%.15f' % yc, '%.15f' % zc], capture_output=True, text=True).stdout
    Jt = o.split('J=[[')[1].replace(']', ' ').replace('[', ' ').split(); Jm = np.array([[float(Jt[0]), float(Jt[1])], [float(Jt[2]), float(Jt[3])]])
    o2 = subprocess.run(['./horseshoe', 'map', '2', o.split('y=[')[1].split(',')[0], o.split('z=[')[1].split(',')[0]], capture_output=True, text=True).stdout
    Jt2 = o2.split('J=[[')[1].replace(']', ' ').replace('[', ' ').split(); Jm2 = np.array([[float(Jt2[0]), float(Jt2[1])], [float(Jt2[2]), float(Jt2[3])]])
    JJ = Jm2 @ Jm  # numerical DP^4 at the centre
    ev, V = np.linalg.eig(JJ); s = V[:, np.argmin(abs(ev))].real; s = s / np.linalg.norm(s)
    lines.append(f"{name} {yc:.15f} {zc:.15f} {hl:.15e} {a*hl:.15e} {w*s[0]:.15e} {w*s[1]:.15e}")
    print(name, 'eig P^4', ev, 'stable dir', s, file=sys.stderr)
NU = int(sys.argv[2]) if len(sys.argv) > 2 else 400; NS = int(sys.argv[3]) if len(sys.argv) > 3 else 4
for p in ("N1", "N2"):
    for q in ("N1", "N2"): lines.append(f"cover {p} {q} {NU} {NS}")
open('golden.txt', 'w').write("\n".join(lines) + "\n")
