"""h-sets for the PJ winner (B = Theta, G = kappa/gamma_rel), P^1 golden-mean graph N1->N1, N1->N2, N2->N1 (geometry is non-rigorous; the check is horseshoe_bg)."""
import numpy as np, subprocess, os, sys
env = dict(os.environ, FSOT_B='0.91751027120648765', FSOT_G='0.73504813634763333')
P = np.loadtxt('sec_pj.txt'); Y, Z = P[:, 0], P[:, 1]
sets = {'N1': (float(sys.argv[1]), float(sys.argv[2])), 'N2': (float(sys.argv[3]), float(sys.argv[4]))}
w = float(sys.argv[5]) if len(sys.argv) > 5 else 1e-3
lines = ["# PJ P^1 h-sets (golden-mean graph). Generated by mk_hsets_pj.py", "iterate 1"]
for name, (y0, y1) in sets.items():
    yc = 0.5 * (y0 + y1); hl = 0.5 * (y1 - y0)
    # attractor sheet nearest to the median: use the densest z cluster in the window
    m = np.abs(Y - yc) < hl; zz = Z[m]; hist, edges = np.histogram(zz, 40); zc0 = 0.5 * (edges[hist.argmax()] + edges[hist.argmax() + 1])
    mm = m & (np.abs(Z - (zc0 + 0 * Y)) < 0.05); a, b = np.polyfit(Y[mm], Z[mm], 1); zc = a * yc + b
    o = subprocess.run(['./horseshoe_bg', 'map', '1', '%.15f' % yc, '%.15f' % zc], capture_output=True, text=True, env=env).stdout
    Jt = o.split('J=[[')[1].replace(']', ' ').replace('[', ' ').split(); J = np.array([[float(Jt[0]), float(Jt[1])], [float(Jt[2]), float(Jt[3])]])
    ev, V = np.linalg.eig(J); s = V[:, np.argmin(abs(ev))].real; s /= np.linalg.norm(s)
    lines.append(f"{name} {yc:.15f} {zc:.15f} {hl:.15e} {a*hl:.15e} {w*s[0]:.15e} {w*s[1]:.15e}")
    print(name, yc, zc, 'slope', a, 'eig', ev, file=sys.stderr)
for p, q in (("N1", "N1"), ("N1", "N2"), ("N2", "N1")): lines.append(f"cover {p} {q} 400 4")
open('golden_pj.txt', 'w').write("\n".join(lines) + "\n")
